apiVersion: v1
kind: Pod
metadata:
  name: logging-mock-service-pod
spec:
  containers:
    - name: logging-mock-service
      image: logging-mock-service:latest
      imagePullPolicy: IfNotPresent
    
